version: "2"
services:
  s-b-a:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=springbatchdb

